### PR TITLE
Minor load-time speedups / code formatting

### PR DESCRIPTION
**Pull request by ribasushi**
Each commit should speak for itself. As a result (of unscientific eyeball-benchmark) load time goes from 19ms down to 9ms.

### CODE REVIEW

**Comment by ribasushi** [comment]
@frioux Not sure if this will highlight you, so making it so.

**Comment by ribasushi** [comment]
(tangentially) Rofl. Apparently github orders stuff in the PR-view by date, *NOT* by ancestry. For example 931d848 is contained in both a797b05 and adaf24d

/cc @kentfredric - you seem to like such curiosities ;)

**Comment by frioux** [comment]
Cool! I'll see if I can merge and release this before I leave OSCON

-- 
sent from a rotary phone, pardon my brevity

**Comment by ribasushi** [comment]
This has been addressed by https://metacpan.org/release/FREW/Sub-Exporter-Progressive-0.001012 ( release HEAD in https://github.com/frioux/Sub-Exporter-Progressive/commit/234e0f66af7f )

Thanks!

**Pull request closed without merging**
